trigger: none

variables:
- name: azureServiceConnection
  value: azurerm-terraform-backend
- name: resourceGroup
  value: rg-tfstate
- name: storageAccount
  value: tfstate7a4c4iw4gbetk
- name: container
  value: terraform-state
- name: tfStateKey
  value: petclinic.tfstate
- group: terraform-prod-vars

stages:
- stage: Destroy
  displayName: Terraform Destroy
  jobs:
  - deployment: DestroyJob
    displayName: DESTROY PetClinic Infrastructure
    environment: production
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: latest

          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: azurerm
              command: init
              backendServiceArm: $(azureServiceConnection)
              backendAzureRmResourceGroupName: $(resourceGroup)
              backendAzureRmStorageAccountName: $(storageAccount)
              backendAzureRmContainerName: $(container)
              backendAzureRmKey: $(tfStateKey)

          - task: TerraformTaskV4@4
            displayName: Terraform Destroy
            inputs:
              provider: azurerm
              command: destroy
              commandOptions: -var="admin_password=$(TF_VAR_admin_password)"
              environmentServiceNameAzureRM: $(azureServiceConnection)